from flask import Flask, request
from flask_cors import CORS, cross_origin
from gpt3 import GPTRunning, setOpenai

setOpenai("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")

app = Flask(__name__, template_folder='templates')
cors = CORS(app)
app.config['CORS_HEADERS'] = 'Content-Type'

# configurate the folder for csv files that uploaded by users
UPLOAD_FOLDER = 'data'
app.config['UPLOAD_FOLDER'] = UPLOAD_FOLDER


@app.route('/', methods=['POST', 'GET'])
@cross_origin()
def mainPage():
  response = {}
  if request.method == 'POST':
    uploadFile = request.files['csvFile']
    instruction = request.form['instruction']
    fileName = uploadFile.filename
    uploadFile.save(fileName)
    GPTRunningInstance = GPTRunning(fileName)

    # run gpt3
    response = GPTRunningInstance.getCode(instruction)

    # run code that is generated by gpt3
    GPTRunningInstance.getOutput()

    return response

  return response


if __name__ == "__main__":
  app.run(debug=True)
